// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "speaker.h"
#include <stdio.h>

/* RS485 동기화 중 슬라이더 이벤트가 STBY로 되돌리는 것을 방지 */
static uint8_t s_rs485_syncing = 0;
static uint8_t s_active_slider = 0;  /* 0=Level(Slider2), 1=Depth(Slider1) */

/* ── HP 로컬 상태 변수 (my_tasks.c 정의) ──
 *  GUI 조작 → 로컬 상태만 업데이트.
 *  Main이 @Q 폴링하면 RS485 태스크가 이 값들을 읽어 응답.
 *  HP는 자율 송신하지 않음 (슬레이브). */
extern volatile uint8_t g_rf_power;       /* PWR 슬라이더 0~9 */

/* ── 슬라이더 노브 위에 라벨을 배치하는 헬퍼 ──
 *  LVGL vertical slider 의 노브는 bar 영역 안에서 움직이되,
 *  value=max 일 때 노브 "anchor" 가 bar top 에 위치하고 노브 자체는
 *  pad_top 만큼 위로 연장된다. → label 을 노브 중심에 두려면
 *  knob_h/2 만큼 위로 보정 필요.                                            */
static void slider_label_follow_knob(lv_obj_t *label, lv_obj_t *slider)
{
    int val = lv_slider_get_value(slider);
    int mn  = lv_slider_get_min_value(slider);
    int mx  = lv_slider_get_max_value(slider);
    if (mx == mn) return;

    lv_coord_t sy = lv_obj_get_style_y(slider, 0);   /* slider y 오프셋 (-50) */
    lv_coord_t sh = lv_obj_get_height(slider);        /* 120 */
    lv_coord_t sw = lv_obj_get_width(slider);         /* 25 */
    lv_coord_t bar_top = sy - sh / 2;                 /* -110 */

    /* knob 높이는 vertical slider 에서 slider 폭과 비슷 (square knob). */
    lv_coord_t knob_h = sw;
    float ratio = (float)(val - mn) / (float)(mx - mn);
    /* knob 중심 y = bar_top + (1 - ratio) * sh - knob_h/2
     *   ratio=1 (max): bar_top - knob_h/2  (knob 이 bar top 위로 연장)
     *   ratio=0 (min): bar_top + sh - knob_h/2  (knob 이 bar bottom 안쪽) */
    lv_coord_t knob_y = bar_top + (lv_coord_t)((1.0f - ratio) * (float)sh) - knob_h / 2;
    lv_obj_set_y(label, knob_y);
}

lv_obj_t * uic_ImgButton1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_LabelPWR = NULL;
lv_obj_t * ui_LabelNEEDLE = NULL;
lv_obj_t * ui_LabelCenterValue = NULL;

/* ── 중앙 상단 값 표시 갱신 (활성 슬라이더 기준) ── */
static void update_center_value(void)
{
    if (!ui_LabelCenterValue) return;
    char buf[8];
    if (s_active_slider == 0) {
        /* Level: Slider2 내부 0-9 → 표시 1-10 */
        lv_snprintf(buf, sizeof(buf), "%d", (int)lv_slider_get_value(ui_Slider2) + 1);
    } else {
        /* Depth: Slider1 내부 0-6 → 표시 0.5~3.5 (step 0.5) */
        int v = lv_slider_get_value(ui_Slider1) * 5 + 5;
        lv_snprintf(buf, sizeof(buf), "%d.%d", v / 10, v % 10);
    }
    lv_label_set_text(ui_LabelCenterValue, buf);
}

// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    // Guard: Slider1/Slider2 already have dedicated handlers.
    // Without this guard, bubbled VALUE_CHANGED from ImgButton1
    // calls lv_slider_get_value() on a non-slider → garbage digits.
    (void)e;
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        /* CHECKED = READY(1), UNCHECKED = STBY(0) */
        extern volatile uint8_t g_gui_ready;
        g_gui_ready = lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED) ? 1U : 0U;

        /* ── 버튼 라벨 텍스트 변경 ── */
        lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
        if(label) lv_label_set_text(label, g_gui_ready ? "TREAT" : "STBY");

        /* ── 사운드 출력 ── */
        Speaker_Play(g_gui_ready ? SND_READY : SND_STBY);

        /* g_gui_ready 는 위에서 설정 완료 → Main @Q 폴링 시 응답에 반영 */
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_PRESSED) {
        s_active_slider = 0;
        update_center_value();
    }

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        /* Level: 내부 0-9, 표시 1-10, 노브 위에 따라다님 */
        { char buf[8]; lv_snprintf(buf, sizeof(buf), "%d", (int)lv_slider_get_value(target) + 1);
          lv_label_set_text(ui_Label2, buf); }
        slider_label_follow_knob(ui_Label2, target);
        /* 드래그 중 update_center_value() 생략 — release 에서 한 번만 갱신 (응답성 향상) */

        if (s_rs485_syncing) {
            /* RS485 동기화 중: 슬라이더 라벨만 갱신, STBY 전환 안함 */
            return;
        }

        /* READY → STBY 자동 전환 (사용자 터치 시에만) */
        extern volatile uint8_t g_gui_ready;
        if (lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED)) {
            lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
            lv_obj_invalidate(ui_ImgButton1);  /* 강제 갱신 */
            lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
            if(label) lv_label_set_text(label, "STBY");
        }
        g_gui_ready = 0U;  /* 슬라이더 변경 시 항상 STBY */

        /* PWR 로컬 상태 업데이트 (내부 0-9) */
        g_rf_power = (uint8_t)lv_slider_get_value(target);
    }

    if(event_code == LV_EVENT_RELEASED) {
        /* 드래그 종료: 중앙 값 최종 갱신 */
        update_center_value();
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_PRESSED) {
        s_active_slider = 1;
        update_center_value();
    }

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        /* Depth: 내부 0-6 → 0.5~3.5mm (step 0.5).  ×10 정수로 표시 */
        int v = lv_slider_get_value(target) * 5 + 5;   /* 5..35 = 0.5..3.5mm ×10 */
        { char buf[8]; lv_snprintf(buf, sizeof(buf), "%d.%d", v / 10, v % 10);
          lv_label_set_text(ui_Label1, buf); }
        slider_label_follow_knob(ui_Label1, target);

        if (s_rs485_syncing) {
            /* RS485 동기화 중: 라벨만 갱신, STBY 전환/깊이쓰기 안함 */
            return;
        }

        /* READY → STBY 자동 전환 (사용자 터치 시에만) — Slider2 와 동일 안전패턴 */
        extern volatile uint8_t g_gui_ready;
        if (lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED)) {
            lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
            lv_obj_invalidate(ui_ImgButton1);  /* 강제 갱신 */
            lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
            if(label) lv_label_set_text(label, "STBY");
        }
        g_gui_ready = 0U;  /* 슬라이더 변경 시 항상 STBY */

        /* Depth 로컬 상태 업데이트 → OP_ 머신이 다음 PUSH 시 target_depth 로 사용 */
        extern volatile float g_needle_depth_mm;
        g_needle_depth_mm = (float)v / 10.0f;   /* 0.5 ~ 3.5 */
    }

    if(event_code == LV_EVENT_RELEASED) {
        /* 드래그 종료: 중앙 값 최종 갱신 */
        update_center_value();
    }
}

/* ═══════════════════════════════════════════════════════════
 *  RS485 → UI 동기화 콜백 (LVGL 스레드에서 50ms 주기 실행)
 *
 *  rs485_process()가 B/R/S/P/N 커맨드 수신 시
 *  로컬 상태를 업데이트하고 g_ui_update_pending=1 설정.
 *  이 타이머가 LVGL 스레드에서 UI를 갱신한다.
 * ═══════════════════════════════════════════════════════════*/
static void ui_rs485_sync_cb(lv_timer_t *timer)
{
    (void)timer;
    extern volatile uint8_t g_ui_update_pending;
    if (!g_ui_update_pending) return;
    g_ui_update_pending = 0;

    extern volatile uint8_t g_gui_ready;
    extern volatile float   g_needle_depth_mm;

    /* ── 가드 플래그 ON: 슬라이더 이벤트가 STBY로 되돌리지 않도록 ── */
    s_rs485_syncing = 1;

    /* ── PWR 변경 감지 시 중앙 값 표시를 Level 로 전환 ── */
    {
        int old_pwr = lv_slider_get_value(ui_Slider2);
        int new_pwr = (int)g_rf_power;
        if (new_pwr != old_pwr) s_active_slider = 0;
    }

    /* ── 슬라이더 먼저 업데이트 (이벤트 발생해도 가드가 차단) ── */

    /* PWR 슬라이더 (Slider2, 0~9, 표시 1~10) */
    lv_slider_set_value(ui_Slider2, (int32_t)g_rf_power, LV_ANIM_OFF);
    { char buf[8]; lv_snprintf(buf, sizeof(buf), "%d", (int)g_rf_power + 1);
      lv_label_set_text(ui_Label2, buf); }
    slider_label_follow_knob(ui_Label2, ui_Slider2);

    /* NEEDLE 슬라이더 (Slider1) — g_needle_depth_mm(0.5~3.5) → 내부 0~6 반영
     *  (s_rs485_syncing 가드로 위 슬라이더 이벤트는 깊이쓰기 없이 라벨만 갱신) */
    {
        int sv = (int)((g_needle_depth_mm * 10.0f - 5.0f) / 5.0f + 0.5f);
        if (sv < 0) sv = 0; else if (sv > 6) sv = 6;
        lv_slider_set_value(ui_Slider1, (int32_t)sv, LV_ANIM_OFF);
        int dv = sv * 5 + 5;
        char buf[8]; lv_snprintf(buf, sizeof(buf), "%d.%d", dv / 10, dv % 10);
        lv_label_set_text(ui_Label1, buf);
        slider_label_follow_knob(ui_Label1, ui_Slider1);
    }

    /* 중앙 상단 값 갱신 */
    update_center_value();

    /* ── READY/STBY 버튼 (마지막에 설정 — 슬라이더가 덮어쓰지 못함) ── */
    {
        uint8_t was_checked = lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED) ? 1 : 0;
        if (g_gui_ready) {
            if (!was_checked)
                lv_obj_add_state(ui_ImgButton1, LV_STATE_CHECKED);
        } else {
            if (was_checked)
                lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
        }
        /* 상태 변경 시 사운드 출력 (READY↔STBY 전환) */
        if (was_checked != g_gui_ready) {
            Speaker_Play(g_gui_ready ? SND_READY : SND_STBY);
        }
    }
    lv_obj_invalidate(ui_ImgButton1);
    lv_obj_t *lbl = lv_obj_get_child(ui_ImgButton1, 0);
    if (lbl) lv_label_set_text(lbl, g_gui_ready ? "TREAT" : "STBY");

    /* ── 가드 플래그 OFF ── */
    s_rs485_syncing = 0;
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_style_all(ui_Screen1);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE);

    /* ─────────────────────────────────────────────────────────
     * 배경색을 Screen이 아닌 별도 자식 패널에 설정.
     * Screen 자체는 완전 투명 → 어떤 상태(PRESSED/CHECKED/FOCUSED)
     * 변경이 발생해도 화면 배경색이 절대 바뀌지 않음.
     * ───────────────────────────────────────────────────────── */
    lv_obj_t * ui_BgPanel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_BgPanel);
    lv_obj_set_size(ui_BgPanel, LV_PCT(100), LV_PCT(100));
    lv_obj_set_pos(ui_BgPanel, 0, 0);
    lv_obj_clear_flag(ui_BgPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE |
        LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_set_style_bg_color(ui_BgPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BgPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ImgButton1, 240);
    lv_obj_set_height(ui_ImgButton1, 80);
    lv_obj_set_x(ui_ImgButton1, 2);
    lv_obj_set_y(ui_ImgButton1, 101);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton1, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    /* ── 전환 애니메이션 제거 (즉시 변환) ── */
    static lv_style_transition_dsc_t tr_instant;
    static lv_style_prop_t tr_props[] = {LV_STYLE_BG_COLOR, LV_STYLE_SHADOW_COLOR,
        LV_STYLE_SHADOW_OPA, LV_STYLE_SHADOW_WIDTH, LV_STYLE_BORDER_COLOR, 0};
    lv_style_transition_dsc_init(&tr_instant, tr_props, lv_anim_path_linear, 0, 0, NULL);
    lv_obj_set_style_transition(ui_ImgButton1, &tr_instant, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transition(ui_ImgButton1, &tr_instant, LV_PART_MAIN | LV_STATE_CHECKED);

    /* ── STBY state (unchecked) : vivid blue ── */
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ImgButton1, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ImgButton1, lv_color_hex(0x60B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImgButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── READY state (checked) : vivid red ── */
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0xFF2020), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ImgButton1, lv_color_hex(0xFF2020), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ImgButton1, lv_color_hex(0xFF7070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ImgButton1, 2, LV_PART_MAIN | LV_STATE_CHECKED);

    /* ── Button label ── */
    lv_obj_t * ui_BtnLabel = lv_label_create(ui_ImgButton1);
    lv_label_set_text(ui_BtnLabel, "STBY");
    lv_obj_center(ui_BtnLabel);
    lv_obj_set_style_text_color(ui_BtnLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnLabel, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPWR = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelPWR, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelPWR, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelPWR, -77);
    lv_obj_set_y(ui_LabelPWR, 35);
    lv_obj_set_align(ui_LabelPWR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPWR, "Level");
    lv_obj_set_style_text_color(ui_LabelPWR, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPWR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPWR, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNEEDLE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelNEEDLE, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelNEEDLE, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelNEEDLE, 75);
    lv_obj_set_y(ui_LabelNEEDLE, 35);
    lv_obj_set_align(ui_LabelNEEDLE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNEEDLE, "Depth");
    lv_obj_set_style_text_color(ui_LabelNEEDLE, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNEEDLE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNEEDLE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider2, 0, 9);
    lv_slider_set_value(ui_Slider2, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 40);   /* 막대 폭 25→40 (잡기 쉽게) */
    lv_obj_set_height(ui_Slider2, 120);
    lv_obj_set_x(ui_Slider2, -77);
    lv_obj_set_y(ui_Slider2, -50);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x04FC04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── Slider2 indicator: bright green glow ── */
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0x00E000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    /* ── Slider2 knob: red (Label2 font color) ── */
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFD050E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xB00308), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Slider2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x1C1C24), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider2, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider2, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider2, 18, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider2, 18, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_ext_click_area(ui_Slider2, 50);  /* 터치 확장 영역 (25→50: 손가락 hit 쉽게) */

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 0, 6);        /* 0.5~3.5mm, step 0.5mm */
    lv_slider_set_value(ui_Slider1, 6, LV_ANIM_OFF);   /* Depth 전원투입 기본값 3.5mm (조절 가능) */
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 40);   /* 막대 폭 25→40 (잡기 쉽게) */
    lv_obj_set_height(ui_Slider1, 120);
    lv_obj_set_x(ui_Slider1, 75);
    lv_obj_set_y(ui_Slider1, -50);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x05FD05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── Slider1 indicator: bright green glow ── */
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0x00E000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    /* ── Slider1 knob: yellow (Label1 font color) ── */
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFDD203), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0xB09502), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Slider1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x1C1C24), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 18, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 18, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_ext_click_area(ui_Slider1, 50);  /* 터치 확장 영역 (25→50: 손가락 hit 쉽게) */

    /* ── 값 라벨: 슬라이더보다 나중에 생성 → 노브 위에 그려짐 ── */
    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label2, -77);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "6");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label1, 75);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "3.5");  /* Depth 잠금 표시 */
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── 중앙 상단 값 표시 라벨 (현재 활성 슬라이더 값) ── */
    ui_LabelCenterValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCenterValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelCenterValue, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LabelCenterValue, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_LabelCenterValue, 2);
    lv_label_set_text(ui_LabelCenterValue, "6");  /* 초기값: Level 슬라이더 기본값 */
    lv_obj_set_style_text_color(ui_LabelCenterValue, lv_color_hex(0x39FF14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCenterValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCenterValue, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    /* Screen1 이벤트 제거 — 배경색 변경 방지 */
    uic_ImgButton1 = ui_ImgButton1;

    /* ── 라벨 초기 위치 ── */
    slider_label_follow_knob(ui_Label2, ui_Slider2);   /* PWR: 노브 따라다님 */

    /* Depth 라벨도 Level(Label2)과 똑같이 follow_knob 로 초기 배치한다.
     *  [근본원인] lv_obj_align_to() 는 내부에서 라벨 align 을 LV_ALIGN_TOP_LEFT
     *  로 바꾼다(lv_obj_pos.c:482). 반면 slider_label_follow_knob() 의 knob_y 는
     *  슬라이더 sy(=-50, CENTER 기준)에서 계산한 '음수' 좌표라 CENTER align
     *  라벨에서만 맞다. 그래서 드래그 때 follow_knob 가 TOP_LEFT 라벨에
     *  set_y(음수) 하면 라벨이 화면 위로 날아가 "3.5" 가 사라졌다.
     *  (Label2 는 계속 CENTER 라 정상) → Level 과 동일하게 통일. */
    slider_label_follow_knob(ui_Label1, ui_Slider1);

    update_center_value();  /* 중앙 값 초기화 */

    /* RS485 수신 → UI 동기화 타이머 (20ms 주기, LVGL 스레드에서 실행) */
    lv_timer_create(ui_rs485_sync_cb, 20, NULL);
}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_ImgButton1 = NULL;
    ui_ImgButton1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Slider2 = NULL;
    ui_Slider1 = NULL;
    ui_LabelPWR = NULL;
    ui_LabelNEEDLE = NULL;
    ui_LabelCenterValue = NULL;

}
