// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// SPLASH SCREEN
static lv_obj_t * ui_SplashScreen = NULL;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif


///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

/* ── Splash → Screen1 전환 타이머 콜백 ── */
static void splash_timer_cb(lv_timer_t * timer)
{
    lv_disp_load_scr(ui_Screen1);
    if (ui_SplashScreen) {
        lv_obj_del(ui_SplashScreen);
        ui_SplashScreen = NULL;
    }
    lv_timer_del(timer);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    /* ── Splash Screen: DSE INC 2026 (1초 표시) ── */
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_remove_style_all(ui_SplashScreen);
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x3C3C44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * splash_label = lv_label_create(ui_SplashScreen);
    lv_label_set_text(splash_label, "DSE\nINC\n2026");
    lv_obj_set_style_text_color(splash_label, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(splash_label, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(splash_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(splash_label, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(splash_label);

    /* ── 제어 화면 초기화 ── */
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    /* Splash 화면을 먼저 표시, 1초 후 Screen1으로 전환 */
    lv_disp_load_scr(ui_SplashScreen);
    lv_timer_create(splash_timer_cb, 2000, NULL);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
}
